apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: nginx-permanent
  namespace: base-namespace
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts-repository
        namespace: flux-system
      version: "*"
  interval: 30m0s
  releaseName: nginx-permanent
